# Generated by Django 2.2.7 on 2020-03-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alergyAlert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='how_allergizing',
            field=models.CharField(max_length=50),
        ),
    ]
