# Generated by Django 2.2.7 on 2020-03-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alergyAlert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='how_allergizing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='slug',
            field=models.SlugField(default='existing'),
            preserve_default=False,
        ),
    ]
