# Generated by Django 2.2.7 on 2020-03-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alergyAlert', '0002_auto_20200310_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='how_allergizing',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
