# Generated by Django 2.2.7 on 2020-03-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alergyAlert', '0002_auto_20200306_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
