# Generated by Django 2.2.7 on 2020-03-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alergyAlert', '0003_auto_20200311_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='alergens',
            field=models.ManyToManyField(null=True, to='alergyAlert.Alergen'),
        ),
    ]
